services:
  - type: web
    name: deluxe-frontend
    env: node
    region: oregon
    buildCommand: npm install && npm run build:web
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: EXPO_PUBLIC_API_URL
        value: https://deluxe-backend-1.onrender.com
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
